# ============================
# Servidor
# ============================
server.port=8080

# ============================
# Base de datos PostgreSQL
# ============================
spring.datasource.url=jdbc:postgresql://localhost:5432/xplorenow
spring.datasource.username=xplorenow
spring.datasource.password=xplorenow123
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================
# JPA / Hibernate
# ============================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# ============================
# Cargar data.sql despues de crear el schema
# ============================
spring.sql.init.mode=always

# ============================
# JWT
# ============================
xplorenow.jwt.secret=ESTA-ES-UNA-CLAVE-SUPER-SECRETA-DE-AL-MENOS-32-CARACTERES-PARA-HS256
xplorenow.jwt.expiration-ms=86400000

# ============================
# Logging
# ============================
logging.level.org.springframework.security=DEBUG
logging.level.com.xplorenow=DEBUG


logging.level.org.springframework.jdbc.datasource.init=DEBUG
spring.sql.init.continue-on-error=false
